spring.application.name=curso-introduccion-api-rest

server.port=8092

# Config database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=JDBC:mysql://localhost/db_springboot_dev

# Config Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
